# Generated by Django 2.1.5 on 2019-04-13 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Description of the appointment', max_length=640)),
                ('status', models.CharField(blank=True, choices=[('C', 'Created'), ('a', 'Accepted'), ('p', 'Paid'), ('t', 'Taken'), ('x', 'Cancelled'), ('r', 'Reprogrammed')], default='c', help_text='Appointment Current Status', max_length=1)),
                ('taker_username', models.CharField(help_text='Username of taker user', max_length=20)),
                ('giver_username', models.CharField(help_text='Username of taker user', max_length=20)),
                ('starting_at', models.DateTimeField(help_text='Start datetime')),
                ('ending_at', models.DateTimeField(help_text='Expected end datetime', null=True)),
                ('ended_at', models.DateTimeField(help_text='Effective end datetime', null=True)),
                ('paid', models.DecimalField(decimal_places=4, help_text='Amount paid', max_digits=10)),
                ('feedback', models.CharField(help_text='Feedback given by giver', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Effective end datetime')),
            ],
            options={
                'ordering': ['-id', 'description', 'starting_at'],
            },
        ),
    ]
