# Generated by Django 2.1.5 on 2019-04-14 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['id', 'starting_at']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='giver_username',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='taker_username',
        ),
        migrations.AddField(
            model_name='appointment',
            name='giver_user',
            field=models.ForeignKey(help_text='Giver user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_giver_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='taker_user',
            field=models.ForeignKey(help_text='Taker user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_taker_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
