# Generated by Django 2.1.5 on 2019-05-18 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20190413_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='Effective end datetime', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='feedback',
            field=models.CharField(blank=True, help_text='Feedback given by giver', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='giver_user',
            field=models.ForeignKey(help_text='Giver user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_giver_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Amount paid', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Created'), ('A', 'Accepted'), ('P', 'Paid'), ('T', 'Taken'), ('X', 'Cancelled'), ('R', 'Reprogrammed')], default='c', help_text='Appointment Current Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='taker_user',
            field=models.ForeignKey(help_text='Taker user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment_taker_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
