# Generated by Django 3.0.6 on 2020-06-29 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubniversity', '0003_auto_20200628_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubniversity.Level'),
        ),
    ]
