# Generated by Django 3.0.6 on 2020-07-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubniversity', '0004_auto_20200628_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_name',
            field=models.CharField(default='short name', max_length=16),
            preserve_default=False,
        ),
    ]
