# Generated by Django 3.0.6 on 2020-07-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubniversity', '0005_course_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
