# Generated by Django 3.0.6 on 2020-07-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubniversity', '0006_auto_20200713_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(default='title', max_length=64),
            preserve_default=False,
        ),
    ]
